build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
      

init:
  - "ECHO %PYTHON%"

install:
  - "git submodule init"
  - "git submodule update --recursive"
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install numpy"
  - "%PYTHON%\\python.exe -m pip install ."

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
